<?php 
include __DIR__ . '/header.phtml'; 

// If comment form submitted, get post data and create new comment

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	$commenter = filter_input(INPUT_POST, 'name', FILTER_SANITIZE_STRING);
	$comment = filter_input(INPUT_POST, 'comment', FILTER_SANITIZE_STRING);
	$commenter = trim($commenter);
	$comment = trim($comment);
	if (empty($commenter) || empty($comment)) {
		$alert = '<p class="alert">Please enter all fields</p>';
	} else {
		$newComment = new Comment;
		$newComment->name = $commenter;
		$newComment->body = $comment;
		$newComment->date = date('m/d/Y');
		$newComment->post_id = $post->id;
		$newComment->save();
		$_SESSION['status'] = "Comment added!";
		header("Location: /blog/" . $post->id);
		exit();
	}
}
?>
<section>
	<div class="container">
		<div class="entry-list single">
			<article>
				<?php 
				if (empty($post)) {
					echo '<p class=\"alert\">Sorry, could not find that post</p>';
				} else {
					if (isset($_SESSION['status'])) {
						echo '<p class="alert">'. $_SESSION['status'] . '</p>';
						unset($_SESSION['status']);
					}
					$fullDate = date('F j, Y', strtotime($post->date));
					echo <<<EOT
					<h1>$post->title</h1>
					<time datetime="$post->date">$fullDate</time>
					<div class="entry">
						<p>$post->body</p>
						<p><a class="link" href="/edit/$post->id">Edit Entry</a></p>
					</div>
EOT;
				}
?>			
			</article>
		</div>
	</div>
</section>
<?php if (!empty($post)) {
	echo <<<EOT
<section class="entry-comments">
	<div class="container">
		<h2>Comments</h2>
EOT;
		foreach($comments as $cmt) {
			$fullDate = date('F j, Y', strtotime($cmt->date));
			echo <<<EOT
			<div class="comment">
				<strong>$cmt->name</strong>
				<time datetime="$cmt->date">$fullDate</time>
				<p>$cmt->body</p>
			</div>
EOT;
		}
		echo <<<EOT
		<div class="new-comment">
EOT;
		if (isset($alert)) { echo '<p class="alert">Please enter all fields</p>'; }
		echo <<<EOT
			<form action="/blog/$post->id" method="post">
				  <input type="hidden" name="$nameKey" value="$name">
				  <input type="hidden" name="$valueKey" value="$value">
				  <label for="name"> Name</label>
				  <input type="text" name="name"
EOT;
				  if (!empty($commenter)) { echo "value=$commenter"; }
		echo <<<EOT
				  ><br>
				  <label for="comment">Comment</label>
				  <textarea rows="5" name="comment">
EOT;
				  if (!empty($comment)) { echo $comment; }
		echo <<<EOT
				  </textarea>
				  <input type="submit" value="Post Comment" class="button">
			</form>
		</div>
	</div>
</section>
EOT;
}
?>
<?php include __DIR__ . '/footer.phtml'; ?>