<?php
include __DIR__ . '/header.phtml';

if ($_SERVER['REQUEST_METHOD'] == 'GET') {
	$title = $post->title;
	$entry = $post->body;
}
?>
<section>
	<div class="container">
		<div class="edit-entry">
			<?php 
			if (empty($post)) {
				echo "<p style=\"color: red; font-size: 1.5em; text-align: center;\">Sorry, could not find that post</p>";
			} else {
?>
			<h2>Edit Entry</h2>
			<form action=">
				<label for="title"> Title</label>
				<input type="text" name="title" value="<?php echo $post->title; ?>"><br>
				<label for="entry">Entry</label>
				<textarea rows="5" name="entry"><?php echo $post->body; ?></textarea>
				<input type="submit" value="Save Entry" class="button">
				<a href="#" class="button button-secondary">Cancel</a>
			</form>
			<?php 
			} 
			?>
		</div>
	</div>
</section>
<?php include __DIR__ . '/footer.phtml'; ?>