<?php
include __DIR__ . '/header.phtml';

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	$title = filter_input(INPUT_POST, 'title', FILTER_SANITIZE_STRING);
	$entry = filter_input(INPUT_POST, 'entry', FILTER_SANITIZE_STRING);
	$title = trim($title);
	$entry = trim($entry);
	if (empty($title) || empty($entry)) {
		$status = '<p class="alert">Please enter all fields</p>';
	} else {
		$post->title = $title;
		$post->body = $entry;
		$post->save();
		$_SESSION['status'] = "Post updated!";
		header("Location: /blog/" . $post->id);
		exit();
	}
}
?>
<section>
	<div class="container">
		<div class="edit-entry">
			<?php 
			if (empty($post)) {
				echo '<p class="alert">Sorry, could not find that post</p>';
			} else {
			?>
			<h2>Edit Entry</h2>
			<?php if (isset($status)) { echo $status; } ?>
			<form action="/edit/<?php echo $post->id; ?>" method='POST'>
				<label for="title"> Title</label>
				<input type="hidden" name="<?php echo $nameKey; ?>" value="<?php echo $name; ?>">
				<input type="hidden" name="<?php echo $valueKey; ?>" value="<?php echo $value; ?>">
				<input type="text" name="title" value="<?php 
					if (!empty($title)) { echo $title; } else { echo $post->title; } 
					?>
					"><br>
				<label for="entry">Entry</label>
				<textarea rows="5" name="entry"><?php 
					if (!empty($entry)) { echo $entry; } else { echo $post->body; } 
					?>
					</textarea>
				<input type="submit" value="Save Entry" class="button">
				<a href="/" class="button button-secondary">Cancel</a>
			</form>
			<?php 
			} 
			?>
		</div>
	</div>
</section>
<?php include __DIR__ . '/footer.phtml'; ?>