<?php 
include __DIR__ . '/header.phtml';

// If create post form submitted, get post data and create new post

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	$title = filter_input(INPUT_POST, 'title', FILTER_SANITIZE_STRING);
	$entry = filter_input(INPUT_POST, 'entry', FILTER_SANITIZE_STRING);
	$title = trim($title);
	$entry = trim($entry);
	if (empty($title) || empty($entry)) {
		$alert = '<p class="alert">Please enter all fields</p>';
	} else {
		$post = new Post;
		$post->title = $title;
		$post->body = $entry;
		$post->date = date('m/d/Y g:i');
		$post->save();
		$_SESSION['status'] = "Post added!";
		header("Location: /");
		exit();
	}
}
?>
<section>
	<div class="container">
		<div class="new-entry">
			<h2>Publish New Entry</h2>
			<?php 
			 if (isset($alert)) { echo $alert; };
			?>
			<form action="/new" method="post">
				<input type="hidden" name="<?php echo $nameKey; ?>" value="<?php echo $name; ?>">
				<input type="hidden" name="<?php echo $valueKey; ?>" value="<?php echo $value; ?>">
				<label for="title"> Title</label>
				<input type="text" name="title" value="<?php if (isset($title)) { echo $title; } ?>"><br>
				<label for="entry">Entry</label>
				<textarea rows="5" name="entry"><?php if (isset($entry)) { echo $entry; } ?></textarea>
				<input type="submit" value="Publish Entry" class="button">
				<a href="/" class="button button-secondary">Cancel</a>
			</form>
		</div>
	</div>
</section>
<?php include __DIR__ . '/footer.phtml'; ?>