<?php include __DIR__ . '/header.phtml'; ?>
<section>
	<div class="container">
		<div class="entry-list">
			<?php foreach($posts as $post) {
				$fullDate = date('F j, Y', strtotime($post->date));
				echo <<<EOT
				<article>
					<h2><a href="blog/$post->id">$post->title</a></h2>
					<time datetime="$post->date">$fullDate</time>
				</article>
EOT;
			} 
			?>
		</div>
	</div>
</section>
<?php include __DIR__ . '/footer.phtml'; ?>