<?php include __DIR__ . '/header.phtml'; ?>
<section>
	<?php 
	if (isset($_SESSION['status'])) {
		echo "<p style=\"color: red; text-align: center;\">$_SESSION[status]</p>";
		unset($_SESSION['status']);
	}
	?>
	<div class="container">
		<div class="entry-list">
			<?php foreach($posts as $post) {
				$fullDate = substr_replace($post->date, " at ", 10, 0);
				echo <<<EOT
				<article>
					<h2><a href="blog/$post->id">$post->title</a></h2>
					<time datetime="$post->date">$fullDate</time>
				</article>
EOT;
			} 
			?>
		</div>
	</div>
</section>
<?php include __DIR__ . '/footer.phtml'; ?>